"""empty message

Revision ID: 089943e409c7
Revises: 120a6c7a7530
Create Date: 2018-10-24 19:17:57.128900

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '089943e409c7'
down_revision = '120a6c7a7530'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('header', sa.JSON(), nullable=False))
    op.drop_column('event', 'sex_column')
    op.drop_column('event', 'display_on_visacka_column')
    op.drop_column('event', 'verified_column')
    op.drop_column('event', 'first_name_column')
    op.drop_column('event', 'surname_column')
    op.drop_column('event', 'username_column')
    op.drop_column('event', 'email_column')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('email_column', mysql.VARCHAR(length=2), nullable=False))
    op.add_column('event', sa.Column('username_column', mysql.VARCHAR(length=2), nullable=False))
    op.add_column('event', sa.Column('surname_column', mysql.VARCHAR(length=2), nullable=False))
    op.add_column('event', sa.Column('first_name_column', mysql.VARCHAR(length=2), nullable=False))
    op.add_column('event', sa.Column('verified_column', mysql.VARCHAR(length=2), nullable=False))
    op.add_column('event', sa.Column('display_on_visacka_column', mysql.VARCHAR(length=2), nullable=True))
    op.add_column('event', sa.Column('sex_column', mysql.VARCHAR(length=2), nullable=False))
    op.drop_column('event', 'header')
    # ### end Alembic commands ###
