"""empty message

Revision ID: 120a6c7a7530
Revises: 88ce5f0ce5b1
Create Date: 2018-10-24 19:12:42.126503

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '120a6c7a7530'
down_revision = '88ce5f0ce5b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registration', sa.Column('data', sa.JSON(), nullable=False))
    op.drop_column('registration', 'display_on_visacka')
    op.drop_column('registration', 'email')
    op.drop_column('registration', 'first_name')
    op.drop_column('registration', 'sex')
    op.drop_column('registration', 'username')
    op.drop_column('registration', 'surname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registration', sa.Column('surname', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('registration', sa.Column('username', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('registration', sa.Column('sex', mysql.VARCHAR(length=10), nullable=False))
    op.add_column('registration', sa.Column('first_name', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('registration', sa.Column('email', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('registration', sa.Column('display_on_visacka', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('registration', 'data')
    # ### end Alembic commands ###
