"""empty message

Revision ID: 1800543f3b10
Revises: f71829dbc98d
Create Date: 2018-10-22 09:17:53.339031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1800543f3b10'
down_revision = 'f71829dbc98d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('sex_column', sa.String(length=2), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'sex_column')
    # ### end Alembic commands ###
