"""empty message

Revision ID: 25d9d2e29624
Revises: f727a09dbe98
Create Date: 2018-10-21 22:59:05.639528

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '25d9d2e29624'
down_revision = 'f727a09dbe98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('email_column', sa.String(length=2), nullable=False))
    op.add_column('event', sa.Column('verified_column', sa.String(length=2), nullable=False))
    op.drop_column('event', 'column')
    op.add_column('registration', sa.Column('row', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registration', 'row')
    op.add_column('event', sa.Column('column', mysql.VARCHAR(length=2), nullable=False))
    op.drop_column('event', 'verified_column')
    op.drop_column('event', 'email_column')
    # ### end Alembic commands ###
