"""empty message

Revision ID: 356944164eff
Revises: 802951c3d39b
Create Date: 2019-11-07 10:01:15.464806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '356944164eff'
down_revision = '802951c3d39b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant', 'email')
    # ### end Alembic commands ###
