"""empty message

Revision ID: 39aff9d6f85d
Revises: 1800543f3b10
Create Date: 2018-10-22 10:44:26.770278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39aff9d6f85d'
down_revision = '1800543f3b10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('display_on_visacka_column', sa.String(length=2), nullable=True))
    op.add_column('registration', sa.Column('display_on_visacka', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registration', 'display_on_visacka')
    op.drop_column('event', 'display_on_visacka_column')
    # ### end Alembic commands ###
