"""empty message

Revision ID: 802951c3d39b
Revises: 8af27642433b
Create Date: 2019-11-07 10:00:32.048435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '802951c3d39b'
down_revision = '8af27642433b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('confirmed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant', 'confirmed')
    # ### end Alembic commands ###
