"""empty message

Revision ID: 88ce5f0ce5b1
Revises: e283ebbeb607
Create Date: 2018-10-22 19:58:31.089028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88ce5f0ce5b1'
down_revision = 'e283ebbeb607'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registration', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registration', 'id')
    # ### end Alembic commands ###
