"""empty message

Revision ID: e283ebbeb607
Revises: 39aff9d6f85d
Create Date: 2018-10-22 10:56:17.415719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e283ebbeb607'
down_revision = '39aff9d6f85d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('first_name_column', sa.String(length=2), nullable=False))
    op.add_column('event', sa.Column('username_column', sa.String(length=2), nullable=False))
    op.add_column('registration', sa.Column('first_name', sa.String(length=255), nullable=False))
    op.add_column('registration', sa.Column('username', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registration', 'username')
    op.drop_column('registration', 'first_name')
    op.drop_column('event', 'username_column')
    op.drop_column('event', 'first_name_column')
    # ### end Alembic commands ###
