"""empty message

Revision ID: f71829dbc98d
Revises: 25d9d2e29624
Create Date: 2018-10-22 09:14:41.606620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f71829dbc98d'
down_revision = '25d9d2e29624'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('surname_column', sa.String(length=2), nullable=False))
    op.add_column('registration', sa.Column('sex', sa.String(length=10), nullable=False))
    op.add_column('registration', sa.Column('surname', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registration', 'surname')
    op.drop_column('registration', 'sex')
    op.drop_column('event', 'surname_column')
    # ### end Alembic commands ###
