# Generated by Django 2.1.3 on 2018-11-21 14:08

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_table', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('list_name', models.CharField(blank=True, max_length=255)),
                ('header', jsonfield.fields.JSONField(default=[])),
                ('skip_rows', models.IntegerField(default=0)),
                ('from_mail', models.CharField(blank=True, max_length=255)),
                ('successfully_confirmed_url', models.CharField(blank=True, max_length=255)),
                ('invalid_token_url', models.CharField(blank=True, max_length=255)),
                ('already_confirmed_url', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MailText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_type', models.CharField(choices=[('confirm', 'Confirm registration'), ('verify', 'Verify registration')], max_length=255)),
                ('text', models.TextField(blank=True, help_text="This has same syntax like Django's templates. You can use any data from registration JSON here")),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventsite.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('data', jsonfield.fields.JSONField()),
                ('verified', models.BooleanField(default=False)),
                ('confirmed', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventsite.Event')),
            ],
        ),
    ]
