# Generated by Django 2.1.3 on 2018-11-23 13:52

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('eventsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='data',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
