# Generated by Django 2.1.3 on 2018-11-23 13:22

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('eventsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('open', 'Open-ended question'), ('close', 'Close-ended question')], max_length=255)),
                ('possible_answers', jsonfield.fields.JSONField(default=[])),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventsite.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventsite.Registration'),
        ),
        migrations.AddField(
            model_name='event',
            name='questions',
            field=models.ManyToManyField(to='eventsite.Question'),
        ),
    ]
