# Generated by Django 2.1.3 on 2018-11-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsite', '0002_auto_20181123_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='questions',
            field=models.ManyToManyField(blank=True, to='eventsite.Question'),
        ),
    ]
