# Generated by Django 2.1.3 on 2018-11-23 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventsite', '0003_auto_20181123_1323'),
        ('eventsite', '0002_auto_20181123_1327'),
        ('eventsite', '0002_auto_20181123_1352'),
    ]

    operations = [
    ]
