# Generated by Django 2.1.3 on 2018-11-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsite', '0004_merge_20181123_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='registration',
        ),
        migrations.AddField(
            model_name='registration',
            name='answers',
            field=models.ManyToManyField(to='eventsite.Answer'),
        ),
    ]
