# Generated by Django 2.1.3 on 2018-11-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsite', '0005_auto_20181123_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurnameCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominative', models.CharField(blank=True, max_length=255)),
                ('vocative', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
